name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75ddf028817eae279fc26a4a53ca0a5d70cd7654e1f0fbb18d35ab6689ccd501"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
