name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91c29041b2c7ebc812f68168ee96b979198e9a43091d3e9921e962479b0fd737"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
