name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6413f0c68d4ec1db402621a9f543c9e9d0e0d2c7a20a2a5a040fe705a51469ea"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
