name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1d5642b916203678143fcb519b46bb5b6c26cf0e25566bb876700d778dbbed0"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
