name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "635c18c099e0a62119e55c8ddac1900e4cfea54096ef6b87e6e4a6baa1c2426a"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
