name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e100a2eef63812b836187eda5c1e2752d9b484082812a97161e8b8368a35a71"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
