name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4e72015d0bd2dd4fc983b3b68d779230cf65613225b43d7a016bc1a5a13ebbe"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
