name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3301daaa9a0619cecd624d5ac409a2504e58da03bd36697856f6eb81ee14566f"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
