name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3109b6d0c658ebe8525ed47a55409ffa4525d3266c63f88672930adc3d202324"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
