name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0c748f898c5391c812cc1a02fe178ee7a920a1c61c957678db337d300b874d3"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
