name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d414b00f2978676e44ee88783c362db6654bb8d0f27e8924e38f01ba63a420be"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
