name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8195c3fc5517807e3003a346e2888660dcbe872f1ccaa103bcc5755cfe57509e"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
