name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07bc0c785fc6f28cc840b854da22bb7d37df188137d0e60b7f998e50c7cac690"

[versions]
forge = "47.0.0"
minecraft = "1.20.1"
