name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac32c338e4a54b59ad99fafb057ca8195984169268f1ad9d90dceb9dacff0d9f"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
