name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9be9bad7503ab7c5b52124d5251ee57063ba51db31f164c83b829265336da832"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
