name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cf1f2ede1dbc46b7be42d52f2e78bfc83342427ea3de53c71b11084e7b91879"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
