name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd719e3f4b43796a13630a657cfc8a1ce30b64a7bb80614b8327e78333c21f45"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
