name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd4ef791fa8dcf59220535a2f3498d39d9fe2ec813f82530616de80bec030c45"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
