name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdcf3cb6c27f3964a3a9e24ca9dbb6f1bc385f8ac083a7a659cdd0250ee3ee76"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
