name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79e9ef540a4d9fdb3c22ec44bb6e5163fee9cc3f8e7939ab9177b13fb461e67a"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
