name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73e421d5b7ff9007455019062f09228c81d6f3b6a4e99f75f9e9e2ada1c56132"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
