name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f5da13d70952dbe4f71170e1fc9f01d52523e7a2735af917b2749c3f46ba5ae"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
