name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f5760ea8ee62524a3d01a288d68e62e5f7b5ff38cb38da14390d5918209033d"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
