name = "Origin Echoes"
author = "flutterbyskies"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c092852d430f830d0932ad2901b7a249b4f4e44746f84cc83f041b09e062cc1"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
